name: Minigames
version: ${project.version}
main: de.blxckoxymoron.minigames.Minigames
api-version: 1.16
authors: [ Oxymoron ]

commands:
  arena:
    usage: "§cUsage: §e/arena <§6create§e|§6delete§e|§6teleport§e|§6edit§e> <§6name§e>"
    description: edit arenas